const records = [
  { id: 'PUC-26-041', label: 'Comfortable PASS', vehicle: 'MH 12 KYP 4021', type: 'Petrol car', date: '20 Aug 2026', note: 'Both measurements are comfortably below the displayed limits.', pollutants: [{ name: 'CO', full: 'Carbon monoxide', value: 0.24, limit: 0.5, unit: '% vol', about: 'Carbon monoxide is a gas produced when fuel does not burn completely.' }, { name: 'HC', full: 'Hydrocarbons', value: 42, limit: 100, unit: 'ppm', about: 'Hydrocarbons are unburnt fuel particles released in vehicle exhaust.' }] },
  { id: 'PUC-26-118', label: 'Near-limit PASS', vehicle: 'DL 3C KYP 8118', type: 'Petrol car', date: '21 Aug 2026', note: 'The result passes, but CO is close to the displayed limit.', pollutants: [{ name: 'CO', full: 'Carbon monoxide', value: 0.46, limit: 0.5, unit: '% vol', about: 'Carbon monoxide is a gas produced when fuel does not burn completely.' }, { name: 'HC', full: 'Hydrocarbons', value: 74, limit: 100, unit: 'ppm', about: 'Hydrocarbons are unburnt fuel particles released in vehicle exhaust.' }] },
  { id: 'PUC-26-207', label: 'FAIL', vehicle: 'KA 01 KYP 9207', type: 'Petrol car', date: '22 Aug 2026', note: 'HC is above the displayed limit.', pollutants: [{ name: 'CO', full: 'Carbon monoxide', value: 0.31, limit: 0.5, unit: '% vol', about: 'Carbon monoxide is a gas produced when fuel does not burn completely.' }, { name: 'HC', full: 'Hydrocarbons', value: 132, limit: 100, unit: 'ppm', about: 'Hydrocarbons are unburnt fuel particles released in vehicle exhaust.' }] }
];

let selected = records[2];
let page = 'home';
let activePollutant = null;

function analysis(record) {
  const results = record.pollutants.map(p => ({ ...p, percent: Math.round((p.value / p.limit) * 100), state: p.value > p.limit ? 'over' : p.value / p.limit >= .8 ? 'near' : 'good' }));
  return { results, pass: results.every(p => p.state !== 'over') };
}
function stateLabel(s) { return s === 'over' ? 'Over limit' : s === 'near' ? 'Near limit' : 'Within limit'; }
function statusCopy(result) { return result.pass ? (result.results.some(x => x.state === 'near') ? 'Your result passes. One measurement is close to the displayed limit.' : 'Your result passes. All shown measurements are within the displayed limits.') : 'Your result does not pass because one or more measurements are over the displayed limit.'; }
function nav() { return `<header><button class="brand" onclick="go('home')" aria-label="Go home"><span class="brand-mark">K</span><span>Know Your <b>PUC</b></span></button><span class="prototype">Prototype · mock data</span></header>`; }
function disclosure() { return `<aside class="disclosure"><b>Prototype disclosure</b><span>This is a student prototype using simulated certificate records and illustrative rules. It is not connected to, endorsed by, or affiliated with Parivahan Sewa or any government system.</span></aside>`; }
function go(next) { page = next; activePollutant = null; render(); window.scrollTo({top: 0, behavior: 'smooth'}); }
function choose(id) { selected = records.find(r => r.id === id); go('dashboard'); }
function render() {
  const views = { home, dashboard, detail, help, next, report };
  document.getElementById('app').innerHTML = nav() + views[page]() + disclosure();
}
function home() { return `<section class="hero"><div class="eyebrow">A simpler PUC journey</div><h1>Technical result.<br><em>Clear next step.</em></h1><p>Know Your PUC turns a Pollution Under Control result into an understandable emissions and action report.</p><button class="primary" onclick="go('dashboard')">View a mock PUC result <span>→</span></button><div class="journey"><div><b>1</b><span>Choose a result</span></div><div><b>2</b><span>Understand it</span></div><div><b>3</b><span>Know what to do</span></div></div></section><section class="why"><p class="eyebrow">Designed for citizens</p><h2>Numbers alone don’t explain the result.</h2><p>See each measurement against its displayed limit, in plain language, on any phone.</p></section>`; }
function recordPicker() { return `<div class="picker"><p class="eyebrow">Choose a demo record</p><div class="record-options">${records.map(r => `<button class="record ${r.id === selected.id ? 'selected' : ''}" onclick="choose('${r.id}')"><span class="dot ${r.label.includes('FAIL') ? 'red' : r.label.includes('Near') ? 'amber' : 'green'}"></span><span><b>${r.label}</b><small>${r.vehicle} · ${r.note}</small></span><span>›</span></button>`).join('')}</div></div>`; }
function dashboard() { const a = analysis(selected); return `<section class="screen"><a class="back" onclick="go('home')">← Start over</a>${recordPicker()}<div class="result-card ${a.pass ? 'pass' : 'fail'}"><div><span class="status-pill">${a.pass ? 'PASS' : 'FAIL'}</span><h1>${a.pass ? 'Your result is within the displayed limits.' : 'Your result needs attention.'}</h1><p>${statusCopy(a)}</p></div><div class="result-ring">${a.pass ? '✓' : '!'}</div></div><div class="meta"><span><b>Vehicle</b>${selected.vehicle}</span><span><b>Type</b>${selected.type}</span><span><b>Test date</b>${selected.date}</span></div><section class="section"><div class="section-head"><div><p class="eyebrow">Your measurements</p><h2>What the numbers mean</h2></div><span class="mini">Tap for detail</span></div><div class="pollutants">${a.results.map((p,i) => `<button class="pollutant ${p.state}" onclick="openDetail(${i})"><div class="pollutant-top"><span><b>${p.name}</b><small>${p.full}</small></span><span class="tag">${stateLabel(p.state)}</span></div><div class="measure"><strong>${p.value} <small>${p.unit}</small></strong><span>Limit: ${p.limit} ${p.unit}</span></div><div class="bar"><i style="width:${Math.min(p.percent,100)}%"></i></div><span class="percent">${p.percent}% of displayed limit <b>→</b></span></button>`).join('')}</div></section><div class="actions"><button class="secondary" onclick="go('help')">Ask about this result</button><button class="primary" onclick="go('next')">See next step <span>→</span></button></div></section>`; }
function openDetail(i) { activePollutant = analysis(selected).results[i]; page = 'detail'; render(); window.scrollTo(0,0); }
function detail() { const p = activePollutant || analysis(selected).results[0]; const desc = p.state === 'over' ? `This value is above the displayed limit by ${(p.value-p.limit).toFixed(p.unit === '% vol' ? 2 : 0)} ${p.unit}.` : p.state === 'near' ? 'This value is still within the displayed limit, but it is close to it.' : 'This value is comfortably within the displayed limit.'; return `<section class="screen narrow"><a class="back" onclick="go('dashboard')">← Back to result</a><p class="eyebrow">Pollutant detail</p><h1>${p.name}: ${p.full}</h1><p class="lead">${p.about}</p><div class="compare ${p.state}"><div><small>Your value</small><b>${p.value} <em>${p.unit}</em></b></div><div><small>Displayed limit</small><b>${p.limit} <em>${p.unit}</em></b></div></div><div class="plain"><span>In plain language</span><p>${desc} The comparison shown here uses the prototype’s configured data, not an AI-generated limit.</p></div><div class="environment"><b>Why it matters</b><p>These exhaust measurements can affect local air quality. A PUC result does not measure a vehicle’s total climate footprint.</p></div><button class="primary full" onclick="go('next')">See your next step <span>→</span></button></section>`; }
function next() { const a = analysis(selected); const isNear = a.results.some(x => x.state === 'near'); const title = a.pass ? (isNear ? 'It passes. Keep an eye on the close measurement.' : 'It passes. Keep this result for your records.') : 'Arrange inspection, then retest.'; const body = a.pass ? (isNear ? 'Your selected record is within the displayed limits. Regular vehicle care and future testing can help you track the measurement that is closest to its limit.' : 'All measurements in this selected record are within the displayed limits. Follow the usual testing schedule applicable to your vehicle.') : 'One or more measurements in this selected record are over the displayed limit. Consider having the vehicle inspected or maintained, then take a new test. This prototype cannot identify a mechanical cause.'; return `<section class="screen narrow"><a class="back" onclick="go('dashboard')">← Back to result</a><div class="next-icon">${a.pass ? '✓' : '→'}</div><p class="eyebrow">Your next step</p><h1>${title}</h1><p class="lead">${body}</p><div class="checklist"><b>What to do now</b><ol>${a.pass ? '<li>Keep the result for your records.</li><li>Follow your normal testing schedule.</li>' : '<li>Arrange an inspection or maintenance visit.</li><li>Retest after the issue has been addressed.</li>'}</ol></div><div class="actions"><button class="secondary" onclick="go('help')">Ask a question</button><button class="primary" onclick="go('report')">View simple report <span>→</span></button></div></section>`; }
function help() { const a = analysis(selected); return `<section class="screen narrow"><a class="back" onclick="go('dashboard')">← Back to result</a><p class="eyebrow">Guided help</p><h1>Ask about this result</h1><p class="lead">Answers use only the selected prototype record and its configured information.</p><div class="questions"><button onclick="answer('fail')">Why did I ${a.pass ? 'pass' : 'fail'}?</button><button onclick="answer('co')">What is CO?</button><button onclick="answer('close')">Which measurement is closest to the limit?</button><button onclick="answer('next')">What should I do next?</button></div><div id="answer" class="answer"><b>Try a suggested question</b><p>I’ll explain the selected record without inventing limits or diagnosing the vehicle.</p></div></section>`; }
function answer(q) { const a = analysis(selected), closest = [...a.results].sort((x,y)=>y.percent-x.percent)[0]; const text = { fail: a.pass ? 'This selected record passes because every shown measurement is at or below its configured limit.' : `This selected record fails because ${a.results.filter(x=>x.state==='over').map(x=>x.name).join(' and ')} is above its configured limit.`, co: 'CO means carbon monoxide. It is a gas produced when fuel does not burn completely. This prototype can explain the result, but cannot identify a vehicle fault.', close: `${closest.name} is closest to its displayed limit: ${closest.value} ${closest.unit}, or ${closest.percent}% of that limit.`, next: a.pass ? 'Keep the result for your records and follow the normal testing schedule. This is informational guidance, not a legal determination.' : 'Arrange inspection or maintenance and retest afterward. The available certificate data is not enough to identify a mechanical cause.' }; const target = document.getElementById('answer'); target.innerHTML = `<b>Answer based on ${selected.id}</b><p>${text[q]}</p>`; }
function report() { const a = analysis(selected); return `<section class="screen report"><a class="back no-print" onclick="go('dashboard')">← Back to result</a><div class="report-head"><span class="brand-mark">K</span><div><p class="eyebrow">Simplified PUC report</p><h1>${a.pass ? 'PASS' : 'FAIL'}</h1></div></div><p class="lead">${statusCopy(a)}</p><div class="report-meta"><span><b>Vehicle</b>${selected.vehicle}</span><span><b>Test date</b>${selected.date}</span><span><b>Record</b>${selected.id}</span></div><table><thead><tr><th>Pollutant</th><th>Your value</th><th>Displayed limit</th><th>Result</th></tr></thead><tbody>${a.results.map(p=>`<tr><td><b>${p.name}</b><small>${p.full}</small></td><td>${p.value} ${p.unit}</td><td>${p.limit} ${p.unit}</td><td><span class="tag ${p.state}">${stateLabel(p.state)}</span></td></tr>`).join('')}</tbody></table><div class="plain"><span>Next step</span><p>${a.pass ? 'Keep this result for your records and follow the normal testing schedule.' : 'Arrange inspection or maintenance, then retest. This report does not diagnose a vehicle fault.'}</p></div><div class="actions no-print"><button class="secondary" onclick="copyReport()">Copy summary</button><button class="primary" onclick="window.print()">Save / print report</button></div></section>`; }
function copyReport() { const a=analysis(selected); navigator.clipboard?.writeText(`Know Your PUC — ${a.pass?'PASS':'FAIL'}\nVehicle: ${selected.vehicle}\n${a.results.map(p=>`${p.name}: ${p.value} ${p.unit}; displayed limit ${p.limit} ${p.unit}; ${stateLabel(p.state)}`).join('\n')}`).then(()=>alert('Report summary copied.')); }
render();
