const records = [
  { id: 'PUC-26-041', label: 'Comfortable PASS', vehicle: 'DL 01 XX 2002', type: 'Petrol car', date: '10 Jan 2027', note: 'All measurements are comfortably within the displayed limits.', pollutants: [{ name: 'CO', full: 'Carbon monoxide', value: 0.14, limit: 0.30, unit: '%', displayLimit: '0.30%', about: 'Carbon monoxide is a gas produced when fuel does not burn completely.' }, { name: 'HC', full: 'Hydrocarbons', value: 42, limit: 200, unit: 'ppm', displayLimit: '200ppm', about: 'Hydrocarbons are unburnt fuel particles released in vehicle exhaust.' }, { name: 'Lambda', full: 'Air-fuel combustion indicator', value: 1.01, limit: 1.03, unit: '', displayLimit: '0.97–1.03', state: 'good', percent: 50, about: 'Lambda indicates how closely the air and fuel mixture matches the expected combustion range.' }] },
  { id: 'PUC-26-118', label: 'Near-limit PASS', vehicle: 'DL 01 XX 2002', type: 'Petrol car', date: '10 Jan 2027', note: 'CO is close to the displayed limit.', pollutants: [{ name: 'CO', full: 'Carbon monoxide', value: 0.27, limit: 0.30, unit: '%', displayLimit: '0.30%', about: 'Carbon monoxide is a gas produced when fuel does not burn completely.' }, { name: 'HC', full: 'Hydrocarbons', value: 185, limit: 200, unit: 'ppm', displayLimit: '200ppm', about: 'Hydrocarbons are unburnt fuel particles released in vehicle exhaust.' }, { name: 'Lambda', full: 'Air-fuel combustion indicator', value: 1.03, limit: 1.03, unit: '', displayLimit: '0.97–1.03', state: 'near', percent: 100, about: 'Lambda indicates how closely the air and fuel mixture matches the expected combustion range.' }] },
  { id: 'PUC-26-207', label: 'FAIL', vehicle: 'DL 01 XX 2002', type: 'Petrol car', date: '10 Jan 2027', note: 'CO and HC are above the displayed limits.', pollutants: [{ name: 'CO', full: 'Carbon monoxide', value: 0.42, limit: 0.30, unit: '%', displayLimit: '0.30%', about: 'Carbon monoxide is a gas produced when fuel does not burn completely.' }, { name: 'HC', full: 'Hydrocarbons', value: 260, limit: 200, unit: 'ppm', displayLimit: '200ppm', about: 'Hydrocarbons are unburnt fuel particles released in vehicle exhaust.' }, { name: 'Lambda', full: 'Air-fuel combustion indicator', value: 1.01, limit: 1.03, unit: '', displayLimit: '0.97–1.03', state: 'good', percent: 50, about: 'Lambda indicates how closely the air and fuel mixture matches the expected combustion range.' }] }
];

let selected = records[2];
let page = 'home';
let activePollutant = null;
let loginError = '';

function analysis(record) {
  const results = record.pollutants.map(p => ({ ...p, percent: p.percent ?? Math.round((p.value / p.limit) * 100), state: p.state ?? (p.value > p.limit ? 'over' : p.value / p.limit >= .8 ? 'near' : 'good') }));
  return { results, pass: results.every(p => p.state !== 'over') };
}
function stateLabel(s) { return s === 'over' ? 'Over limit' : s === 'near' ? 'Near limit' : 'Within limit'; }
function statusCopy(result) { return result.pass ? (result.results.some(x => x.state === 'near') ? 'Your result passes. One measurement is close to the displayed limit.' : 'Your result passes. All shown measurements are within the displayed limits.') : 'Your result does not pass because one or more measurements are over the displayed limit.'; }
function nav() { return `<header><button class="brand" onclick="go('home')" aria-label="Go home"><span class="brand-mark">K</span><span>Know Your <b>PUC</b></span></button><span class="prototype">Prototype</span></header>`; }
function disclosure() { return `<aside class="disclosure"><b>Prototype disclosure</b><span>This is a student prototype using simulated certificate records and illustrative rules. It is not connected to, endorsed by, or affiliated with Parivahan Sewa or any government system.</span></aside>`; }
function go(next) { page = next; activePollutant = null; render(); window.scrollTo({top: 0, behavior: 'smooth'}); }
function choose(id) { selected = records.find(r => r.id === id); go('dashboard'); }
function render() {
  const views = { home, login, dashboard, detail, help, next, report };
  document.getElementById('app').innerHTML = nav() + views[page]() + disclosure();
}
function home() { return `<section class="hero"><div class="eyebrow">A simpler PUC journey</div><h1>Technical result.<br><em>Clear next step.</em></h1><p>Know Your PUC turns a Pollution Under Control result into an understandable emissions and action report.</p><button class="primary" onclick="go('login')">Login <span>→</span></button><div class="journey"><div><b>1</b><span>Choose a result</span></div><div><b>2</b><span>Understand it</span></div><div><b>3</b><span>Know what to do</span></div></div></section><section class="why"><p class="eyebrow">Designed for citizens</p><h2>Numbers alone don’t explain the result.</h2><p>See each measurement against its displayed limit, in plain language, on any phone.</p></section>`; }
function login() { return `<style>.login-card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:32px}.login-card label{display:block;font-weight:700;margin:20px 0 8px}.login-card input{display:block;width:100%;padding:14px;border:1px solid var(--line);border-radius:10px;font:inherit}.login-card input:focus{outline:3px solid #cce9dc;border-color:var(--green)}.login-error{color:var(--red);margin:16px 0 0}</style><section class="screen narrow login-screen"><a class="back" onclick="go('home')">← Back to home</a><div class="login-card"><p class="eyebrow">Secure access</p><h1>Login to view your PUC result</h1><p class="lead">Enter the details from your vehicle documents.</p><form onsubmit="submitLogin(event)"><label for="vehicle-number">Vehicle number</label><input id="vehicle-number" name="vehicle-number" type="text" placeholder="e.g. DL 01 XX XXXX" autocomplete="username" required><label for="chassis-last-characters">Last 4 characters of chassis</label><input id="chassis-last-characters" name="chassis-last-characters" type="password" placeholder="Enter chassis characters" autocomplete="current-password" minlength="4" maxlength="5" required>${loginError ? `<p class="login-error" role="alert">${loginError}</p>` : ''}<button class="primary full" type="submit">Check my PUC <span>→</span></button></form></div></section>`; }
function submitLogin(event) { event.preventDefault(); const form = event.currentTarget; const vehicleNumber = form.elements['vehicle-number'].value.trim().replace(/\s+/g, ' ').toUpperCase(); const chassisCharacters = form.elements['chassis-last-characters'].value.trim(); if (vehicleNumber === 'DL 01 XX 2002' && chassisCharacters === '2002') { loginError = ''; selected = records[2]; go('dashboard'); return; } loginError = 'The vehicle number or chassis characters do not match this record.'; render(); }
function selectPucStatus(id) { choose(id); }
function statusButton(id, statusClass, label) { return `<button class="puc-status-option ${statusClass} ${selected.id === id ? 'current' : ''}" type="button" onclick="selectPucStatus('${id}')" aria-pressed="${selected.id === id}" aria-label="View ${label} PUC result">${label}</button>`; }
function recordPicker() { return `<style>.vehicle-profile{background:#fff;border:1px solid var(--line);border-radius:18px;padding:22px;margin-bottom:24px}.vehicle-profile>span{display:block;font-weight:800;margin-bottom:8px}.vehicle-profile b{display:block;font-size:1.45rem}.vehicle-profile small{display:block;color:var(--muted);margin-top:5px}.puc-status-title{font-weight:800;margin:26px 0 12px}.puc-status-options{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.puc-status-option{border:0;border-radius:12px;padding:16px 12px;color:var(--ink);font-weight:800;text-align:center;line-height:1.3}.puc-status-option.valid{background:#d9f0e4;color:#19775a}.puc-status-option.near{background:#fff0d4;color:#a96400}.puc-status-option.fail{background:#fee1dc;color:#b83a35}.puc-status-option.current{outline:3px solid currentColor}.puc-status-option:focus-visible{outline:3px solid var(--ink);outline-offset:3px}@media(max-width:680px){.puc-status-options{grid-template-columns:1fr}.vehicle-profile{padding:20px}}</style><div class="vehicle-profile"><span>Your Vehicle:</span><b>DL 01 XX 2002</b><small>Maruti Suzuki • Petrol • 2019</small><p class="puc-status-title">PUC STATUS</p><div class="puc-status-options">${statusButton('PUC-26-041', 'valid', 'VALID')}${statusButton('PUC-26-118', 'near', 'NEAR LIMIT PASS')}${statusButton('PUC-26-207', 'fail', 'FAIL! NEEDS ATTENTION!')}</div></div>`; }
function measurementTable(a) { return `<style>.measurement-table{width:100%;border-collapse:collapse;background:#171717;color:#f8f8f2;border-radius:12px;overflow:hidden}.measurement-table th,.measurement-table td{padding:14px 16px;text-align:left;border-bottom:1px solid #555}.measurement-table th{font-family:'Fraunces',serif;font-size:1rem}.measurement-table tr:last-child td{border-bottom:0}.measurement-table tbody tr{cursor:pointer}.measurement-table tbody tr:hover{background:#262626}.measurement-table tbody tr:focus{outline:3px solid #81e6b2;outline-offset:-3px}.measurement-table td:first-child{font-weight:700}.measurement-table small{color:#c8d0cc;font-weight:400}.status-dot{display:inline-block;width:17px;height:17px;border-radius:50%;background:#55d98a;box-shadow:inset 0 0 5px rgba(255,255,255,.7)}.status-dot.near{background:#ffc95a}.status-dot.over{background:#ff7770}@media(max-width:680px){.measurement-table th,.measurement-table td{padding:12px 8px;font-size:.82rem}.measurement-table th:nth-child(3),.measurement-table td:nth-child(3){display:none}}</style><section class="section"><div class="section-head"><div><p class="eyebrow">Your measurements</p><h2>What the numbers mean</h2></div><span class="mini">Select a row for detail</span></div><table class="measurement-table"><thead><tr><th>Pollutant</th><th>Your result</th><th>Limit</th><th>Status</th></tr></thead><tbody>${a.results.map((p,i) => `<tr tabindex="0" role="button" aria-label="View details for ${p.name}, ${p.full}" onclick="openDetail(${i})" onkeydown="if(event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openDetail(${i}); }"><td>${p.name} <small>(${p.full})</small></td><td>${p.value}${p.unit}</td><td>${p.displayLimit ?? `${p.limit}${p.unit}`}</td><td><span class="status-dot ${p.state}" aria-label="${stateLabel(p.state)}"></span></td></tr>`).join('')}</tbody></table></section>`; }
function dashboard() { const a = analysis(selected); const isNear = a.pass && a.results.some(p => p.state === 'near'); const statusClass = isNear ? 'near' : a.pass ? 'pass' : 'fail'; const statusLabel = isNear ? 'NEAR LIMIT PASS' : a.pass ? 'PASS' : 'FAIL'; const statusTitle = isNear ? 'Your result is within limits, but close to the edge.' : a.pass ? 'Your result is within the displayed limits.' : 'Your result needs attention.'; const statusText = isNear ? 'Your result passes, but one or more measurements are close to the limit. Consider getting your vehicle checked soon.' : statusCopy(a); const statusIcon = isNear ? '⚠️' : a.pass ? '✓' : '!'; return `<section class="screen"><a class="back" onclick="go('home')">← Start over</a>${recordPicker()}<div class="result-card ${statusClass}"><div><span class="status-pill">${statusLabel}</span><h1>${statusTitle}</h1><p>${statusText}</p></div><div class="result-ring">${statusIcon}</div></div><div class="meta"><span><b>Vehicle</b>${selected.vehicle}</span><span><b>Type</b>${selected.type}</span><span><b>Test date</b>${selected.date}</span></div>${measurementTable(a)}<style>.result-card.near{background:#fff0d4}.measurement-table{background:#fff;color:var(--ink);border:1px solid var(--line);border-collapse:separate;border-spacing:0;border-radius:14px}.measurement-table th,.measurement-table td{border-bottom:1px solid var(--line);padding:16px}.measurement-table th{background:#edf4f0;color:var(--muted);font-family:'DM Sans',sans-serif;font-size:.74rem;letter-spacing:.07em;text-transform:uppercase}.measurement-table tbody tr:hover{background:#f2fbf6}.measurement-table tbody tr:focus{outline:3px solid var(--green);outline-offset:-3px}.measurement-table small{color:var(--muted)}.status-dot{width:12px;height:12px;box-shadow:none}.status-dot.near{background:var(--amber)}.status-dot.over{background:var(--red)}</style><div class="actions"><button class="secondary" onclick="go('help')">Ask about this result</button><button class="primary" onclick="go('next')">See next step <span>→</span></button></div></section>`; }
function openDetail(i) { activePollutant = analysis(selected).results[i]; page = 'detail'; render(); window.scrollTo(0,0); }
function limitLabel(p) { return p.displayLimit ?? `${p.limit}${p.unit}`; }
function detail() { const p = activePollutant || analysis(selected).results[0]; const desc = p.state === 'over' ? `This value is above the displayed limit by ${(p.value-p.limit).toFixed(p.unit === '%' ? 2 : 0)} ${p.unit}.` : p.state === 'near' ? 'This value is still within the displayed limit, but it is close to it.' : 'This value is comfortably within the displayed limit.'; return `<section class="screen narrow"><a class="back" onclick="go('dashboard')">← Back to result</a><p class="eyebrow">Pollutant detail</p><h1>${p.name}: ${p.full}</h1><p class="lead">${p.about}</p><div class="compare ${p.state}"><div><small>Your value</small><b>${p.value}${p.unit ? ` <em>${p.unit}</em>` : ''}</b></div><div><small>Displayed limit</small><b>${limitLabel(p)}</b></div></div><div class="plain"><span>In plain language</span><p>${desc} The comparison shown here uses the prototype’s configured data, not an AI-generated limit.</p></div><div class="environment"><b>Why it matters</b><p>These exhaust measurements can affect local air quality. A PUC result does not measure a vehicle’s total climate footprint.</p></div><button class="primary full" onclick="go('next')">See your next step <span>→</span></button></section>`; }
function next() { const a = analysis(selected); const isNear = a.results.some(x => x.state === 'near'); const title = a.pass ? (isNear ? 'It passes. Keep an eye on the close measurement.' : 'It passes. Keep this result for your records.') : 'Arrange inspection, then retest.'; const body = a.pass ? (isNear ? 'Your selected record is within the displayed limits. Regular vehicle care and future testing can help you track the measurement that is closest to its limit.' : 'All measurements in this selected record are within the displayed limits. Follow the usual testing schedule applicable to your vehicle.') : 'One or more measurements in this selected record are over the displayed limit. Consider having the vehicle inspected or maintained, then take a new test. This prototype cannot identify a mechanical cause.'; return `<section class="screen narrow"><a class="back" onclick="go('dashboard')">← Back to result</a><div class="next-icon">${a.pass ? '✓' : '→'}</div><p class="eyebrow">Your next step</p><h1>${title}</h1><p class="lead">${body}</p><div class="checklist"><b>What to do now</b><ol>${a.pass ? '<li>Keep the result for your records.</li><li>Follow your normal testing schedule.</li>' : '<li>Arrange an inspection or maintenance visit.</li><li>Retest after the issue has been addressed.</li>'}</ol></div><div class="actions"><button class="secondary" onclick="go('help')">Ask a question</button><button class="primary" onclick="go('report')">View simple report <span>→</span></button></div></section>`; }
function help() { const a = analysis(selected); return `<section class="screen narrow"><a class="back" onclick="go('dashboard')">← Back to result</a><p class="eyebrow">Guided help</p><h1>Ask about this result</h1><p class="lead">Answers use only the selected prototype record and its configured information.</p><div class="questions"><button onclick="answer('fail')">Why did I ${a.pass ? 'pass' : 'fail'}?</button><button onclick="answer('co')">What is CO?</button><button onclick="answer('close')">Which measurement is closest to the limit?</button><button onclick="answer('next')">What should I do next?</button></div><div id="answer" class="answer"><b>Try a suggested question</b><p>I’ll explain the selected record without inventing limits or diagnosing the vehicle.</p></div></section>`; }
function answer(q) { const a = analysis(selected), closest = [...a.results].sort((x,y)=>y.percent-x.percent)[0]; const text = { fail: a.pass ? 'This selected record passes because every shown measurement is at or below its configured limit.' : `This selected record fails because ${a.results.filter(x=>x.state==='over').map(x=>x.name).join(' and ')} is above its configured limit.`, co: 'CO means carbon monoxide. It is a gas produced when fuel does not burn completely. This prototype can explain the result, but cannot identify a vehicle fault.', close: `${closest.name} is closest to its displayed limit: ${closest.value} ${closest.unit}, or ${closest.percent}% of that limit.`, next: a.pass ? 'Keep the result for your records and follow the normal testing schedule. This is informational guidance, not a legal determination.' : 'Arrange inspection or maintenance and retest afterward. The available certificate data is not enough to identify a mechanical cause.' }; const target = document.getElementById('answer'); target.innerHTML = `<b>Answer based on ${selected.id}</b><p>${text[q]}</p>`; }
function report() { const a = analysis(selected); return `<section class="screen report"><a class="back no-print" onclick="go('dashboard')">← Back to result</a><div class="report-head"><span class="brand-mark">K</span><div><p class="eyebrow">Simplified PUC report</p><h1>${a.pass ? 'PASS' : 'FAIL'}</h1></div></div><p class="lead">${statusCopy(a)}</p><div class="report-meta"><span><b>Vehicle</b>${selected.vehicle}</span><span><b>Test date</b>${selected.date}</span><span><b>Record</b>${selected.id}</span></div><table><thead><tr><th>Pollutant</th><th>Your value</th><th>Displayed limit</th><th>Result</th></tr></thead><tbody>${a.results.map(p=>`<tr><td><b>${p.name}</b><small>${p.full}</small></td><td>${p.value} ${p.unit}</td><td>${p.limit} ${p.unit}</td><td><span class="tag ${p.state}">${stateLabel(p.state)}</span></td></tr>`).join('')}</tbody></table><div class="plain"><span>Next step</span><p>${a.pass ? 'Keep this result for your records and follow the normal testing schedule.' : 'Arrange inspection or maintenance, then retest. This report does not diagnose a vehicle fault.'}</p></div><div class="actions no-print"><button class="secondary" onclick="copyReport()">Copy summary</button><button class="primary" onclick="window.print()">Save / print report</button></div></section>`; }
function copyReport() { const a=analysis(selected); navigator.clipboard?.writeText(`Know Your PUC — ${a.pass?'PASS':'FAIL'}\nVehicle: ${selected.vehicle}\n${a.results.map(p=>`${p.name}: ${p.value} ${p.unit}; displayed limit ${p.limit} ${p.unit}; ${stateLabel(p.state)}`).join('\n')}`).then(()=>alert('Report summary copied.')); }
render();
